### ISSUE TITLE
Investigate alternate color schemes

### ISSUE THREAD

**Issue by matthewbrown77** [matthewbrown77/matthewbrown77.github.io#7]

**Comment by dollyjain51099** [comment]
I would like to work on this issue, please assign it to me!

**Comment by matthewbrown77** [comment]
Sure. Please report any color scheme changes you think improves the look or design of the site.

**Comment by dollyjain51099** [comment]
![image](https://user-images.githubusercontent.com/54888610/103145910-4765f580-4767-11eb-96ef-5b96ac9160d2.png)
I have modified the background using css gradient, kindly comment on the color scheme whether it looks good!

**Comment by matthewbrown77** [comment]
Wow this looks awesome! Feel free to create a merge request for these changes.

**Comment by dollyjain51099** [comment]
I have created a PR for the same, please accept it!
